# Generated by Django 5.1.5 on 2025-02-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_scraper', '0002_remove_produto_imagem_imagemproduto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.TextField(),
        ),
    ]
