# Generated by Django 5.1.5 on 2025-02-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_scraper', '0003_alter_produto_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='link',
            field=models.URLField(max_length=500),
        ),
    ]
